### ISSUE TITLE
Geoserver is not accessible Illegal access

### ISSUE THREAD

**Issue by lstillwe** [kartoza/docker-geoserver#218]
After pulling docker container : docker pull kartoza/geoserver
... and running : docker run -d --env-file ./env.txt -p 8080:8080 --name geoserver -v /projects:/projects kartoza/geoserver

**curl "http://localhost:8080/geoserver" returns:**
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> The requested resource [&#47;geoserver] is not available</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.43</h3></body></html>

**Error found in catalina.2021-02-16.log on container:**
16-Feb-2021 21:16:43.178 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
16-Feb-2021 21:16:43.192 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [18192] milliseconds
16-Feb-2021 21:16:44.631 INFO [FileSystemWatcher-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.geoserver.platform.resource.ResourceNotification$Kind]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.geoserver.platform.resource.ResourceNotification$Kind]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
		at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1384)
		at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1372)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1225)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1187)
		at org.geoserver.platform.resource.FileSystemWatcher$Watch.pollDirectory(FileSystemWatcher.java:220)
		at org.geoserver.platform.resource.FileSystemWatcher$Watch.changed(FileSystemWatcher.java:210)
		at org.geoserver.platform.resource.FileSystemWatcher$1.run(FileSystemWatcher.java:341)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by NyakudyaA** [comment]
Can you please share the logs when geoserver is starting

**Comment by NyakudyaA** [comment]
Closing due to lack of activity. We using this image daily and runs smoothly

**Comment by nicksilver** [comment]
I know this is closed, but I am having this exact same issue. How do I get the logs when geoserver is starting so that I can share them?

**Comment by nicksilver** [comment]
Ahhh...my issue was fixed by building with the '2.19.0' tag rather than 'latest' per #234

**Comment by NyakudyaA** [comment]
@nicksilver the latest tag was rebuilt earlier using the same recipe as the 2.19.0 image.

Can you pull the latest tag and test again.
If I get time this morning I will test all these tags 2.18.2,2.19.0 and latest fetching the images from dockerhub 

if you need to see the logs you can just start the container and then run `docker logs -f name of container `

**Comment by nicksilver** [comment]
@NyakudyaA I just pulled the kartoza/geoserver:latest build and everything is working beautifully. Thank you!
