### ISSUE TITLE
When I publish shapefile in geoserver cluster, it resports Exception

### ISSUE THREAD

**Issue by PingYufeng** [kartoza/docker-geoserver#390]
`Caused by: java.lang.RuntimeException: Error occurred while building the resources for the configuration page
	at org.geoserver.web.data.layer.NewLayerPage.buildLayerInfo(NewLayerPage.java:431)
	at org.geoserver.web.data.layer.NewLayerPage$9.onClick(NewLayerPage.java:324)
	at org.geoserver.web.wicket.SimpleAjaxLink$1.onClick(SimpleAjaxLink.java:47)
	at org.apache.wicket.ajax.markup.html.AjaxLink$1.onEvent(AjaxLink.java:85)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:155)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:601)
	... 127 more
Caused by: java.lang.NullPointerException
	at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1654)
	at org.geotools.util.NIOUtilities.clean(NIOUtilities.java:190)
	at org.geotools.util.NIOUtilities.clean(NIOUtilities.java:167)
	at org.geotools.data.shapefile.dbf.DbaseFileReader.close(DbaseFileReader.java:303)
	at org.geotools.data.shapefile.ShapefileFeatureSource.readAttributes(ShapefileFeatureSource.java:589)
	at org.geotools.data.shapefile.ShapefileFeatureSource.buildFeatureType(ShapefileFeatureSource.java:482)
	at org.geotools.data.shapefile.ShapefileFeatureStore.buildFeatureType(ShapefileFeatureStore.java:138)
	at org.geotools.data.store.ContentFeatureSource.getAbsoluteSchema(ContentFeatureSource.java:327)
	at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:296)
	at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:105)
	at org.geoserver.catalog.CatalogBuilder.buildFeatureType(CatalogBuilder.java:341)
	at org.geoserver.catalog.CatalogBuilder.buildFeatureType(CatalogBuilder.java:324)
	at org.geoserver.web.data.layer.NewLayerPage.buildLayerInfo(NewLayerPage.java:421)
	... 132 more`

**Comment by NyakudyaA** [comment]
Is this still the case ?
