### ISSUE TITLE
WARN [org.geoserver] - Failed to load logging configuration file 'logging.xml'

### ISSUE THREAD

**Issue by urzds** [kartoza/docker-geoserver#40]
When starting geoserver, I see this:
```
geoserver_1                  | 18 Jul 15:21:32 WARN [org.geoserver] - Failed to load logging configuration file 'logging.xml'
geoserver_1                  | com.thoughtworks.xstream.io.StreamException: 
geoserver_1                  | 	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:126)
geoserver_1                  | 	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
geoserver_1                  | 	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)
geoserver_1                  | 	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)
geoserver_1                  | 	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)
geoserver_1                  | 	at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:63)
geoserver_1                  | 	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
geoserver_1                  | 	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
geoserver_1                  | 	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1346)
geoserver_1                  | 	at org.geoserver.config.util.XStreamPersister.load(XStreamPersister.java:626)
geoserver_1                  | 	at org.geoserver.config.GeoServerLoader.depersist(GeoServerLoader.java:952)
geoserver_1                  | 	at org.geoserver.config.GeoServerLoader.readConfiguration(GeoServerLoader.java:816)
geoserver_1                  | 	at org.geoserver.config.DefaultGeoServerLoader.loadGeoServer(DefaultGeoServerLoader.java:65)
geoserver_1                  | 	at org.geoserver.config.GeoServerLoader.postProcessBeforeInitialization(GeoServerLoader.java:279)
geoserver_1                  | 	at org.geoserver.config.GeoServerLoaderProxy.postProcessBeforeInitialization(GeoServerLoaderProxy.java:59)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
geoserver_1                  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
geoserver_1                  | 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
geoserver_1                  | 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
geoserver_1                  | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
geoserver_1                  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:145)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
geoserver_1                  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
geoserver_1                  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
geoserver_1                  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
geoserver_1                  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
geoserver_1                  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
geoserver_1                  | 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
geoserver_1                  | 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
geoserver_1                  | 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
geoserver_1                  | 	at org.geoserver.platform.GeoServerContextLoaderListener.contextInitialized(GeoServerContextLoaderListener.java:23)
geoserver_1                  | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4900)
geoserver_1                  | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5363)
geoserver_1                  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
geoserver_1                  | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
geoserver_1                  | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:731)
geoserver_1                  | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
geoserver_1                  | 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
geoserver_1                  | 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1868)
geoserver_1                  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
geoserver_1                  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
geoserver_1                  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
geoserver_1                  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
geoserver_1                  | 	at java.lang.Thread.run(Thread.java:748)
geoserver_1                  | Caused by: java.io.EOFException: input contained no data
geoserver_1                  | 	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003)
geoserver_1                  | 	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
geoserver_1                  | 	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410)
geoserver_1                  | 	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
geoserver_1                  | 	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
geoserver_1                  | 	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
geoserver_1                  | 	... 54 more
```

Am I using the image wrongly?

**Comment by NyakudyaA** [comment]
@urzds those are just basic logging errors when Geoserver starts. You can basically fix those if you want but they do not affect Geoserver, they are basically java notifications nothing serious. You can look at the logs in Geoserver and they will be visible. You can configure them in the Global section whether you want verbose or production logs.

With regards to you entry point script. If you can do a PR then we can patch it in.
