### ISSUE TITLE
Geoserver docker image does not start with keycloak plugin activated

### ISSUE THREAD

**Issue by iitsBergenol** [kartoza/docker-geoserver#460]
Hello,

I can't start the geoserver docker image with the community plugin for keycloak activated:

Minimal not working example:

`docker run  -e COMMUNITY_EXTENSIONS=sec-keycloak-plugin -p 8081:8080 kartoza/geoserver:2.21.2`

or as a kubernetes pod definition:

```
apiVersion: v1
kind: Pod
metadata:
  name: geoserver-test-keycloak
spec:
  containers:
  - env:
    - name: COMMUNITY_EXTENSIONS
      value: sec-keycloak-plugin
    - name: GEOSERVER_ADMIN_USER
      value: "admin"
    - name: GEOSERVER_ADMIN_PASSWORD
      value: "admin"
    image: kartoza/geoserver:2.21.2
    name: geoserver-test-keycloak
```

As far as I can see the relevant Log messages says:

```
Caused by: javax.xml.stream.FactoryConfigurationError: Provider for javax.xml.stream.XMLOutputFactory cannot be found
	at java.xml/javax.xml.stream.FactoryFinder.find(FactoryFinder.java:320)
	at java.xml/javax.xml.stream.XMLOutputFactory.newFactory(XMLOutputFactory.java:299)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:124)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:101)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:92)
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:141)
	at rg.springframework.http.converter.json.Jackson2ObjectMapperBuilder$XmlObjectMapperInitializer.create(Jackson2ObjectMapperBuilder.java:888)
	at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.build(Jackson2ObjectMapperBuilder.java:647)
	at org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter.<init>(MappingJackson2XmlHttpMessageConverter.java:52)
	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:86)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.addDefaultHttpMessageConverters(WebMvcConfigurationSupport.java:856)
	at org.geoserver.rest.RestConfiguration.configureMessageConverters(RestConfiguration.java:128)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.getMessageConverters(WebMvcConfigurationSupport.java:809)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.routerFunctionMapping(WebMvcConfigurationSupport.java:515)
	at org.geoserver.rest.RestConfiguration$$EnhancerBySpringCGLIB$$12d4b7cc.CGLIB$routerFunctionMapping$21(<generated>)
	at org.geoserver.rest.RestConfiguration$$EnhancerBySpringCGLIB$$12d4b7cc$$FastClassBySpringCGLIB$$fa40bdb3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.geoserver.rest.RestConfiguration$$EnhancerBySpringCGLIB$$12d4b7cc.routerFunctionMapping(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)

```

**Comment by NyakudyaA** [comment]
Hi, Can you try to add the following env variable `FORCE_DOWNLOAD_COMMUNITY_EXTENSIONS=true`, this will allow the extension to be downloaded again. 

Alternatively try the image 2.22.0 

Note: Community plugins are always in flux state. There is no guarantee that plugins will be accessible between each successive build and will work. You can build the extensions following the guidelines from [GeoServer develop guidelines](https://docs.geoserver.org/latest/en/developer/maven-guide/index.html#building-extensions). If a community extension prevents GeoServer from starting please check stack exchange or report the issue in GeoServer jira

**Comment by iitsBergenol** [comment]
Hi, adding the option to download the extension didn't work. But using the new release of the docker image solved the problem. Thank you.
