### ISSUE TITLE
Geoserver :2.21.2 - Not able to start with the gsr-plugin

### ISSUE THREAD

**Issue by sgavathe** [kartoza/docker-geoserver#467]
I get the below error.  I know its a community plugin. But I was wondering, whom do I contact or where do I fix it ?

`Error creating bean with name 'gsrDispatcher' defined in URL [jar:file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/gs-gsr-2.21-SNAPSHOT.jar!/applicationContext.xml]: `

19 Dec 15:30:05 WARN   [support.XmlWebApplicationContext] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gsrDispatcher' defined in URL [jar:file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/gs-gsr-2.21-SNAPSHOT.jar!/applicationContext.xml]: Initialization of bean failed; nested exception is javax.xml.stream.FactoryConfigurationError: Provider for javax.xml.stream.XMLOutputFactory cannot be found

19 Dec 15:30:05 INFO   [jdbc.JDBCQuotaStore] - Closing up the JDBC quota store 

19 Dec 15:30:05 WARN   [support.DisposableBeanAdapter] - Destroy method 'destroy' on bean with name 'gwcMemoryBlobStore' threw an exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@5c94869b[Not completed, task = org.geowebcache.storage.blobstore.memory.MemoryBlobStore$BlobStoreTask@49338c81] rejected from java.util.concurrent.ThreadPoolExecutor@41a3588d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]

19 Dec 15:30:05 WARN   [support.DisposableBeanAdapter] - Invocation of destroy method failed on bean with name 'geoServerLoader': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'wmsLifecycleHandler': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)

19 Dec 15:30:05 ERROR  [context.ContextLoader] - Context initialization failed

19-Dec-2022 15:30:05.344 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gsrDispatcher' defined in URL [jar:file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/gs-gsr-2.21-SNAPSHOT.jar!/applicationContext.xml]: Initialization of bean failed; nested exception is javax.xml.stream.FactoryConfigurationError: Provider for javax.xml.stream.XMLOutputFactory cannot be found

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)

at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)

at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)

at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)

at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)

at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)

at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)

at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)

at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)

at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)

at org.geoserver.platform.GeoServerContextLoaderListener.contextInitialized(GeoServerContextLoaderListener.java:22)

at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4768)

at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230)

at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)

at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)

at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)

at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1185)

at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1933)

at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)

at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)

at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1095)

at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:477)

at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)

at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)

at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)

at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)

at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)

at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)

at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)

at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)

at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)

at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)

at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)

at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)

at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:265)

at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)

at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)

at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

at org.apache.catalina.startup.Catalina.start(Catalina.java:772)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)

at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)

Caused by: javax.xml.stream.FactoryConfigurationError: Provider for javax.xml.stream.XMLOutputFactory cannot be found

at java.xml/javax.xml.stream.FactoryFinder.find(FactoryFinder.java:320)

at java.xml/javax.xml.stream.XMLOutputFactory.newFactory(XMLOutputFactory.java:299)

at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:124)

at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:101)

at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:92)

at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:141)

at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder$XmlObjectMapperInitializer.create(Jackson2ObjectMapperBuilder.java:888)

at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.build(Jackson2ObjectMapperBuilder.java:647)

at org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter.<init>(MappingJackson2XmlHttpMessageConverter.java:52)

at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:86)

at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.<init>(RequestMappingHandlerAdapter.java:204)

at org.geoserver.ogcapi.APIConfigurationSupport$APIRequestMappingHandlerAdapter.<init>(APIConfigurationSupport.java:35)

at org.geoserver.ogcapi.APIConfigurationSupport.createRequestMappingHandlerAdapter(APIConfigurationSupport.java:82)

at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.requestMappingHandlerAdapter(WebMvcConfigurationSupport.java:613)

at org.geoserver.ogcapi.APIDispatcher.initApplicationContext(APIDispatcher.java:138)

at org.springframework.context.support.ApplicationObjectSupport.setApplicationContext(ApplicationObjectSupport.java:78)

at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:123)

at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:100)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1791)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)

... 53 more

19-Dec-2022 15:30:05.345 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/geoserver] startup failed due to previous errors

19 Dec 15:30:05 INFO   [geoserver.logging] - Beginning GeoServer cleanup sequence

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by org.hsqldb.persist.RAFileNIO (file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/hsqldb-2.4.1.jar) to method java.nio.DirectByteBuffer.cleaner()

WARNING: Please consider reporting this to the maintainers of org.hsqldb.persist.RAFileNIO

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

19-Dec-2022 15:30:06.509 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [geoserver] appears to have started a thread named [JNA Cleaner] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

 java.base@11.0.16/java.lang.Object.wait(Native Method)

 java.base@11.0.16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)

 java.base@11.0.16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)

 com.sun.jna.internal.Cleaner$1.run(Cleaner.java:58)

19-Dec-2022 15:30:06.510 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [geoserver] appears to have started a thread named [FileSystemWatcher-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

 java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)

 java.base@11.0.16/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)

 java.base@11.0.16/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)

 java.base@11.0.16/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)

 java.base@11.0.16/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)

 java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)

 java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)

 java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

 java.base@11.0.16/java.lang.Thread.run(Thread.java:829)

19-Dec-2022 15:30:06.531 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [geoserver] appears to have started a thread named [Timer-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

 java.base@11.0.16/java.lang.Object.wait(Native Method)

 java.base@11.0.16/java.util.TimerThread.mainLoop(Timer.java:553)

 java.base@11.0.16/java.util.TimerThread.run(Timer.java:506)

Thanks,

**Comment by NyakudyaA** [comment]
Please check https://osgeo-org.atlassian.net/jira/software/c/projects/GEOS/issues to see if there are no issues reported there. Some community plugins are not maintained

**Comment by sgavathe** [comment]
@NyakudyaA 

I did search under the JIRA. Didn't find any incident. I will probably have to report it there. Thank you.
