### ISSUE TITLE
Geotiff with Alpha band and JPEG compression fails to render

### ISSUE THREAD

**Issue by kikislater** [kartoza/docker-geoserver#513]
### What is the bug or the crash?

Geotiff with jpeg compression fails to render

Gdalinfo raster : 

```
$ gdalinfo 00_ORTHO_PASSE_DUBOIS_JPEG_50.tif 
Driver: GTiff/GeoTIFF
Files: 00_ORTHO_PASSE_DUBOIS_JPEG_50.tif
Size is 1097, 451
Coordinate System is:
GEOGCRS["WGS 84",
    ENSEMBLE["World Geodetic System 1984 ensemble",
        MEMBER["World Geodetic System 1984 (Transit)"],
        MEMBER["World Geodetic System 1984 (G730)"],
        MEMBER["World Geodetic System 1984 (G873)"],
        MEMBER["World Geodetic System 1984 (G1150)"],
        MEMBER["World Geodetic System 1984 (G1674)"],
        MEMBER["World Geodetic System 1984 (G1762)"],
        MEMBER["World Geodetic System 1984 (G2139)"],
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ENSEMBLEACCURACY[2.0]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (46.203201000000000,-9.408807072101999)
Pixel Size = (0.000010000000000,-0.000010000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=JPEG
  INTERLEAVE=PIXEL
  JPEGTABLESMODE=1
  JPEG_QUALITY=50
Corner Coordinates:
Upper Left  (  46.2032010,  -9.4088071) ( 46d12'11.52"E,  9d24'31.71"S)
Lower Left  (  46.2032010,  -9.4133171) ( 46d12'11.52"E,  9d24'47.94"S)
Upper Right (  46.2141710,  -9.4088071) ( 46d12'51.02"E,  9d24'31.71"S)
Lower Right (  46.2141710,  -9.4133171) ( 46d12'51.02"E,  9d24'47.94"S)
Center      (  46.2086860,  -9.4110621) ( 46d12'31.27"E,  9d24'39.82"S)
Band 1 Block=1097x16 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA 
Band 2 Block=1097x16 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA 
Band 3 Block=1097x16 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA 
Band 4 Block=1097x16 Type=Byte, ColorInterp=Alpha
```

Changing style to raster and moving jpeg to png I got this : 

![image](https://user-images.githubusercontent.com/13238064/228525948-51fdb0d6-cfc1-463a-9778-8a150f66da4a.png)

logs from geoserver:
```
geoserver  | 29 046 11:46:21 ERROR  [geoserver.ows] - 
geoserver  | java.lang.NoClassDefFoundError: org/libjpegturbo/turbojpeg/TJException
geoserver  | 	at org.libjpegturbo.turbojpeg.TJDecompressor.decompress(Native Method)
geoserver  | 	at org.libjpegturbo.turbojpeg.TJDecompressor.decompress(TJDecompressor.java:281)
geoserver  | 	at org.libjpegturbo.turbojpeg.TJDecompressor.decompress(TJDecompressor.java:437)
geoserver  | 	at it.geosolutions.imageio.plugins.turbojpeg.TurboJpegImageReader.read(TurboJpegImageReader.java:149)
geoserver  | 	at java.desktop/javax.imageio.ImageReader.read(ImageReader.java:938)
geoserver  | 	at it.geosolutions.imageioimpl.plugins.tiff.TIFFJPEGDecompressor.decodeRaw(TIFFJPEGDecompressor.java:277)
geoserver  | 	at it.geosolutions.imageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2476)
geoserver  | 	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1795)
geoserver  | 	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:2106)
geoserver  | 	at com.sun.media.jai.imageioimpl.ImageReadOpImage.computeTile(ImageReadOpImage.java:697)
geoserver  | 	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
geoserver  | 	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
geoserver  | 	at javax.media.jai.PlanarImage.cobbleByte(PlanarImage.java:2850)
geoserver  | 	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2169)
geoserver  | 	at it.geosolutions.jaiext.scale.ScaleOpImage.computeTile(ScaleOpImage.java:1651)
geoserver  | 	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
geoserver  | 	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
geoserver  | 	at javax.media.jai.PointOpImage.computeTile(PointOpImage.java:962)
geoserver  | 	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
geoserver  | 	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
geoserver  | 	at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
geoserver  | 	at it.geosolutions.jaiext.mosaic.MosaicOpImage.computeTile(MosaicOpImage.java:833)
geoserver  | 	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
geoserver  | 	at javax.media.jai.OpImage.getTile(OpImage.java:1129)
geoserver  | 	at javax.media.jai.RenderedOp.getTile(RenderedOp.java:2257)
geoserver  | 	at org.geoserver.wms.map.RenderedImageTimeDecorator.getTile(RenderedImageTimeDecorator.java:123)
geoserver  | 	at it.geosolutions.jaiext.colorindexer.PackedHistogram.<init>(PackedHistogram.java:138)
geoserver  | 	at it.geosolutions.jaiext.colorindexer.Quantizer.buildColorIndexer(Quantizer.java:87)
geoserver  | 	at org.geoserver.wms.map.RenderedImageMapResponse.applyPalette(RenderedImageMapResponse.java:182)
geoserver  | 	at org.geoserver.wms.map.PNGMapResponse.formatImageOutputStream(PNGMapResponse.java:97)
geoserver  | 	at org.geoserver.wms.map.RenderedImageMapResponse.write(RenderedImageMapResponse.java:110)
geoserver  | 	at org.geoserver.ows.Dispatcher.response(Dispatcher.java:1018)
geoserver  | 	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:272)
geoserver  | 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
geoserver  | 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
geoserver  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1043)
geoserver  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
geoserver  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
geoserver  | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
geoserver  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:670)
geoserver  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
geoserver  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:356)
geoserver  | 	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:175)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:73)
geoserver  | 	at org.geoserver.ows.HTTPHeadersCollector.doFilter(HTTPHeadersCollector.java:48)
geoserver  | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
geoserver  | 	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:194)
geoserver  | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
geoserver  | 	at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
geoserver  | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
geoserver  | 	at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:144)
geoserver  | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
geoserver  | 	at org.geoserver.params.extractor.Filter.doFilter(Filter.java:138)
geoserver  | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
geoserver  | 	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:43)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:39)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
geoserver  | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
geoserver  | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
geoserver  | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver  | 	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:53)
geoserver  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
geoserver  | 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
geoserver  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver  | 	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
geoserver  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
geoserver  | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
geoserver  | 	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
geoserver  | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver  | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
geoserver  | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
geoserver  | 	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
geoserver  | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
geoserver  | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.geoserver.filters.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:77)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:48)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:49)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
geoserver  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
geoserver  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
geoserver  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
geoserver  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
geoserver  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
geoserver  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
geoserver  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
geoserver  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
geoserver  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
geoserver  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
geoserver  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
geoserver  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
geoserver  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
geoserver  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
geoserver  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
geoserver  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
geoserver  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
geoserver  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
geoserver  | 	at java.base/java.lang.Thread.run(Thread.java:829)
geoserver  | Caused by: java.lang.ClassNotFoundException: org.libjpegturbo.turbojpeg.TJException
geoserver  | 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1412)
geoserver  | 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
geoserver  | 	... 141 more
geoserver  | 29 046 11:46:21 INFO   [geoserver.flow] - releasing flow controllers for [WMS 1.1.1 GetMap]
geoserver  | 29 046 11:46:21 INFO   [geoserver.flow] - Request completed, running requests: 0, blocked requests: 0

```

### Steps to reproduce the issue

- Convert a geotiff to jpeg compresion using 

```
$ gdal_translate -co COMPRESS=JPEG -co JPEG_QUALITY=50 in.tif out.tif
```

- upload to geoserver
- check rendering in preview layer

### Versions

2.21.0 to date

**Comment by NyakudyaA** [comment]
Can you please share a sample data, I can't reproduce with the one I have converted using 
```
gdal_translate -co COMPRESS=JPEG -co JPEG_QUALITY=50 -ot Byte  worldpop_25.tif out.tif
```

**Comment by kikislater** [comment]
Sorry I mean with alpha channel. So as mentionned in Geoserver gitter discussion ( https://app.element.io/#/room/#geoserver_geoserver:gitter.im/$pgM7xx7WRPCE5GNqfGGG2Yits3IF-yT7ajhDRXtpncM ), it will never work: Geoserver doesn't support alpha channel with jpeg compression. 
So a workaround is to you use mask like this : 
```
gdal_translate -co COMPRESS=JPEG -co JPEG_QUALITY=75 -b 1 -b 2 -b 3 -mask 4 -co PHOTOMETRIC=YCBCR --config GDAL_TIFF_INTERNAL_MASK YES in.tif out.tif
```
from here: https://gis.stackexchange.com/questions/361277/geoserver-fails-to-read-a-jpeg-compressed-tiff-with-alpha-band

Sorry for the noise and thanks for this image

**Comment by zhang7249** [comment]
太牛逼了兄弟，全网就你这一个答案，感谢！
