### ISSUE TITLE
Geoserver Startup with taskmanager-core Plugin activated does not work

### ISSUE THREAD

**Issue by DerLinne** [kartoza/docker-geoserver#526]
### What is the bug or the crash?

I tried to activate the taskmanager-core Plugin in our Geoserver Installation. 

I did several different tries:
1. Activate directly in out kubernetes installation
2. Activate on a self build docker image
3. Activate with the docker image for the kartoza geoserver from docker hub.

All tried show the following error during startup - tested with Geoserver Version 2.21, 2.22 and 2.23

```
15:52:46.515 [main] ERROR org.springframework.web.context.ContextLoader - Context initialization failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/gs-taskmanager-core-2.23-SNAPSHOT.jar!/org/geoserver/taskmanager/data/impl/BatchRunImpl.class]; nested exception is java.lang.IllegalArgumentException: Could not find class [javax.persistence.Index]

at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:457) ~[spring-context-5.3.26.jar:5.3.26]

at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:316) ~[spring-context-5.3.26.jar:5.3.26]

at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:276) ~[spring-context-5.3.26.jar:5.3.26]

at org.springframework.context.annotation.ComponentScanBeanDefinitionParser.parse(ComponentScanBeanDefinitionParser.java:90) ~[spring-context-5.3.26.jar:5.3.26]

at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74) ~[spring-beans-5.3.26.jar:5.3.26]

at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1391) ~[spring-beans-5.3.26.jar:5.3.26]

at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1371) ~[spring-beans-5.3.26.jar:5.3.26]
```

When I double check the mentioned jar file and extract it, the missing class is in. 

### Steps to reproduce the issue

Activate the taskmanager core plugin during the deployment.

e.g. set the end variable during docker-compose usage:

```
COMMUNITY_EXTENSIONS="cog-plugin, taskmanager-core-plugin"

```

and start the container. Some seconds after the start, the error comes up. The geoserver startup ends.

### Versions

2.21, 2.22 and 2.23

Perhaps more, but not tested

**Comment by NyakudyaA** [comment]
Have you tried to look upstream in Geoserver jira if there is no open issue, I will debug and see what is wrong later

**Comment by DerLinne** [comment]
I did not find something matching to the problem. But I will check again later.

**Comment by NyakudyaA** [comment]
@DerLinne Try to open  an upstream issue because community plugins are not guaranteed to work

**Comment by DerLinne** [comment]
Ok, we will try this. I'll keep you informed ...

**Comment by DerLinne** [comment]
Hi - i would like to come back with this topic.

Please see here the root cause (I think), the taskmanager was not updated to Java11. 
https://osgeo-org.atlassian.net/browse/GEOS-10968

Following the ticket, this should be resolved since 9th June, but the problem with using this in the docker image is still there.

When I understand the community plugins integration correctly, the plugins are included by default in the current image (we use 2.23.1). Alternatively I force them to download on container start to get the latest code.

Both ways end in the same problem described in the ticket.

Any idea how we can come here to a solution?

**Comment by NyakudyaA** [comment]
@DerLinne I see the ticket is marked as resolved but where is the commit that fixes the issue? We need to check if the dependencies have actually been bundled in the extension.
