### ISSUE TITLE
java.sql.SQLException: Locale not recognized

### ISSUE THREAD

**Issue by jmsierra** [kartoza/docker-geoserver#530]
### What is the bug or the crash?

When using plugin `geoserver-2.20.7-oracle-plugin.zip` with `kartoza/geoserver:2.20.7` the following error is raised:
```
Caused by: java.sql.SQLException: Locale not recognized
        at oracle.jdbc.driver.T4CTTIoauthenticate.setSessionFields(T4CTTIoauthenticate.java:1498)
        at oracle.jdbc.driver.T4CTTIoauthenticate.<init>(T4CTTIoauthenticate.java:294)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:695)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:807)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:77)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:767)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:572)
        at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
        at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
        at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
        ... 155 more
```

This is due to the fact that `entrypoint.sh` sets:
```bash
-Duser.language=${LANGUAGE} \
 -Duser.region=${REGION} \
 -Duser.country=${COUNTRY} \
```

and `$LANGUAGE` is defined from `tomcat:9.0.73-jdk11-temurin-focal` as `en_US:en` which is not a format recognized by the Oracle JDBC driver. 

As workaround I'd overwritten that variable as `ENV LANGUAGE=en` but I reckon there may be better approaches for this.

Many thanks!

### Steps to reproduce the issue

1. Build a docker image with `kartoza/geoserver:2.20.7` and plugin `geoserver-2.20.7-oracle-plugin.zip`
2. Launch container
3. Setup a store with an Oracle connection.
4. Error is raised at connection time. 

### Versions

2.20.7

**Comment by NyakudyaA** [comment]
BY default the language is set as that https://github.com/kartoza/docker-geoserver/blob/develop/scripts/env-data.sh#L148. If the startup is not picking it up then we need to fix

**Comment by jmsierra** [comment]
Yes, I think it's picking it up, but as `tomcat:9.0.73-jdk11-temurin-focal` already defines the environment variable as `en_US:en` geoserver is using it. 
[https://hub.docker.com/layers/library/tomcat/9.0.73-jdk11-temurin-focal/images/sha256-37084b3c596c352c6be2fadffeda308c2cf951a07b668126acfcbd04902e48f9?context=explore](https://hub.docker.com/layers/library/tomcat/9.0.73-jdk11-temurin-focal/images/sha256-37084b3c596c352c6be2fadffeda308c2cf951a07b668126acfcbd04902e48f9?context=explore)

I fixed the issue on my image by adding `ENV LANGUAGE=en` in my Dockerfile. Maybe it wasn't the best solution, but it made the JDBC plugin work.

**Comment by NyakudyaA** [comment]
@jmsierra `LC_ALL` variable is set at the system level and takes precedence over the Java system properties. So to fix this we can add the following env variable 
```
LC_ALL=
```
This will unset the value of LC_ALL and should work in all instances. And a user can still set `LC_ALL=en` to run the image

**Comment by NyakudyaA** [comment]
You can just pass the following env variables

LANGUAGE=en
LANG=en
No need to build a new image
