### ISSUE TITLE
Geoserver Cluster on AWS ECS not working

### ISSUE THREAD

**Issue by ze-ahmed** [kartoza/docker-geoserver#609]
### What is the bug or the crash?

Hello,

I've deployed geoserver on a cluster mode in AWS ECS Cluster.
Not working with kartoza/geoserver:2.24.1 image but works well with geobeyond/geoserver:2.20.6 image

Many thanks in advance for your help

`17:53:24.584 [http-nio-8080-exec-6] ERROR org.geoserver.cluster - No converter available
---- Debugging information ----
message             : No converter available
type                : jdk.internal.misc.InnocuousThread
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private static final jdk.internal.misc.Unsafe jdk.internal.misc.InnocuousThread.UNSAFE accessible: module java.base does not "opens jdk.internal.misc" to unnamed module @6184c0f1
-------------------------------
17:53:24.585 [http-nio-8080-exec-6] WARN  org.geoserver.catalog.impl - Catalog listener threw exception handling event.
java.lang.RuntimeException: Error publishing catalog modified event of type 'CatalogImpl'.
	at org.geoserver.cluster.server.JMSCatalogListener.handleModifyEvent(JMSCatalogListener.java:242) ~[gs-jms-geoserver-2.24-SNAPSHOT.jar:2.24-SNAPSHOT]
	at org.geoserver.catalog.impl.CatalogEventDispatcher.dispatch(CatalogEventDispatcher.java:62) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.catalog.impl.CatalogImpl.event(CatalogImpl.java:1902) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.catalog.impl.CatalogImpl.fireModified(CatalogImpl.java:1876) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.catalog.impl.DefaultCatalogFacade.setDefaultWorkspace(DefaultCatalogFacade.java:819) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.catalog.impl.IsolatedCatalogFacade.setDefaultWorkspace(IsolatedCatalogFacade.java:406) ~[gs-main-2.24.1.jar:2.24.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.geoserver.catalog.LockingCatalogFacade.invoke(LockingCatalogFacade.java:36) ~[gs-main-2.24.1.jar:2.24.1]
	at com.sun.proxy.$Proxy33.setDefaultWorkspace(Unknown Source) ~[?:?]
	at org.geoserver.catalog.impl.CatalogImpl.setDefaultWorkspace(CatalogImpl.java:1557) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.catalog.impl.CatalogImpl.add(CatalogImpl.java:1454) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.security.SecureCatalogImpl.add(SecureCatalogImpl.java:1360) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.catalog.impl.AbstractFilteredCatalog.add(AbstractFilteredCatalog.java:673) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.catalog.impl.AbstractCatalogDecorator.add(AbstractCatalogDecorator.java:716) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.web.data.workspace.WorkspaceNewPage.handleOnSubmit(WorkspaceNewPage.java:170) ~[gs-web-core-2.24.1.jar:2.24.1]
	at org.geoserver.web.data.workspace.WorkspaceNewPage$5.onSubmit(WorkspaceNewPage.java:145) ~[gs-web-core-2.24.1.jar:2.24.1]
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1312) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.markup.html.form.Form.process(Form.java:976) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:797) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:687) ~[wicket-core-7.18.0.jar:7.18.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:216) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:241) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:234) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64) ~[wicket-request-7.18.0.jar:7.18.0]
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.protocol.http.WicketServlet.doPost(WicketServlet.java:159) ~[wicket-core-7.18.0.jar:7.18.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:528) ~[servlet-api.jar:4.0.FR]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596) ~[servlet-api.jar:4.0.FR]
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:166) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:528) ~[servlet-api.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596) ~[servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:328) ~[catalina.jar:9.0.73]
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:158) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28) ~[gs-main-2.24.1.jar:2.24.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:73) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.ows.HTTPHeadersCollector.doFilter(HTTPHeadersCollector.java:48) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.filters.HTTPMethodFilter.doFilter(HTTPMethodFilter.java:36) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:194) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:105) ~[gs-monitor-core-2.24.1.jar:2.24.1]
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89) ~[gs-control-flow-2.24.1.jar:2.24.1]
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:43) ~[gs-main-2.24.1.jar:2.24.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:39) ~[gs-platform-2.24.1.jar:2.24.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:53) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.security.filter.GeoServerUserNamePasswordAuthenticationFilter.doFilter(GeoServerUserNamePasswordAuthenticationFilter.java:122) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:106) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:97) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilterInternal(GeoServerSecurityContextPersistenceFilter.java:72) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75) ~[gs-main-2.24.1.jar:2.24.1]
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186) ~[spring-security-web-5.7.10.jar:5.7.10]
	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142) ~[gs-main-2.24.1.jar:2.24.1]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.geoserver.filters.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:100) ~[gs-main-2.24.1.jar:2.24.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:48) ~[gs-main-2.24.1.jar:2.24.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:49) ~[gs-main-2.24.1.jar:2.24.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42) ~[gs-main-2.24.1.jar:2.24.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:9.0.73]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[catalina.jar:9.0.73]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:9.0.73]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673) ~[catalina.jar:9.0.73]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:9.0.73]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:9.0.73]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389) ~[tomcat-coyote.jar:9.0.73]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:9.0.73]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-coyote.jar:9.0.73]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-coyote.jar:9.0.73]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.73]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.73]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.73]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.73]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: javax.jms.JMSException: No converter available`

### Steps to reproduce the issue

Create an ECS Cluster, EFS for shared data_dir, create an activemq broker
Deploy kartoza/geoserver:2.24.1 image with at least two instances:
When we create for example a workspace in instance1, it does not appear in the second one (if we reload cache it appears), and the above error is found in the logs

### Versions

2.24.1

**Comment by robertd** [comment]
Experiencing similar issues in https://github.com/kartoza/docker-geoserver/issues/595... I've tried running it locally and on ECS. No luck.

**Comment by NyakudyaA** [comment]
How have you deployed this, kubernetes or docker-compose. Are you also using the stand alone JMS broker or the embedded one.

Can you add the following env variable:
```
ADDITIONAL_JAVA_STARTUP_OPTIONS="--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED"
```

**Comment by robertd** [comment]
@ze-ahmed would you mind providing your CloudFormation template?

edit: or terraform :)

**Comment by ze-ahmed** [comment]
@NyakudyaA I've deployed this using AWS ECS (not K8S and not docker-compose), I'm using an external broker.
Even using the env variable 
`ADDITIONAL_JAVA_STARTUP_OPTIONS="--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED"`
it does not work. As I said, with geobeyond/geoserver:2.20.6 image it works fine.

@robertd Sorry but I do not have any template for the moment, I'm doing tests first before generating it

**Comment by NyakudyaA** [comment]
@ze-ahmed Did you also check if the image being pulled correspond to the architecture you are using

**Comment by ze-ahmed** [comment]
@NyakudyaA Even with Arm64 like the image I'm getting exactly the same issue with the image 2..24.1:

`18:13:24.758 [http-nio-8080-exec-5] ERROR org.geoserver.cluster - No converter available
--
---- Debugging information ----
message             : No converter available
type                : jdk.internal.ref.CleanerImpl
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private static java.util.function.Function jdk.internal.ref.CleanerImpl.cleanerImplAccess accessible: module java.base does not "opens jdk.internal.ref" to unnamed module @4a32bc96
-------------------------------
18:13:24.758 [http-nio-8080-exec-5] WARN  org.geoserver.catalog.impl - Catalog listener threw exception handling event.

Thanks in advance for your help
java.lang.RuntimeException: Error publishing catalog modified event of type 'CatalogImpl'.


Caused by: javax.jms.JMSException: No converter available`

**Comment by NyakudyaA** [comment]
@ze-ahmed Would you be interested to take a support contract with us so that we can assist you, it could be a couple of hours because it might be there are some issues we need to take a look I.e configs

**Comment by ze-ahmed** [comment]
Unfortunattely this option is not possible as we are only testing different open source solutions

**Comment by Jason-Daily-Dev** [comment]
I can get it running with ecs, and I used image kartoza/geoserver:latest. My infra is cloudfront -> alb -> ecs geoserver service. For 2.24.1, I got some issues to set up, and forgot to check what errors it ran into.
