### ISSUE TITLE
libjpegturbo broken in wms request

### ISSUE THREAD

**Issue by jeichhor** [kartoza/docker-geoserver#661]
### What is the bug or the crash?

for wms services requesting format=image/jpeg we get the exception below, where the same wms requesting using format=image/png works well.

17 Jun 13:46:37 ERROR  [geoserver.ows] - 
java.lang.UnsatisfiedLinkError: 'int org.libjpegturbo.turbojpeg.TJCompressor.compress(byte[], int, int, int, int, byte[], int, int, int)'
	at org.libjpegturbo.turbojpeg.TJCompressor.compress(Native Method)
	at org.libjpegturbo.turbojpeg.TJCompressor.compress(TJCompressor.java:146)
	at org.libjpegturbo.turbojpeg.TJCompressor.compress(TJCompressor.java:164)
	at it.geosolutions.imageio.plugins.turbojpeg.TurboJpegImageWriter.write(TurboJpegImageWriter.java:201)
	at org.geoserver.map.turbojpeg.TurboJpegImageWorker.writeTurboJPEG(TurboJpegImageWorker.java:126)
	at org.geoserver.map.turbojpeg.TurboJPEGMapResponse.formatImageOutputStream(TurboJPEGMapResponse.java:99)
	at org.geoserver.wms.map.RenderedImageMapResponse.write(RenderedImageMapResponse.java:110)
	at org.geoserver.ows.Dispatcher.response(Dispatcher.java:1034)
	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:273)

### Steps to reproduce the issue

requesting getmap for any layer on service wms

https://localhost:8080/geoserver/myworkspace/wms&
service=WMS&version=1.1.0&
request=GetMap&
layers=myworkspace%3Amylayer&
bbox=1455503.0391517137%2C6859835.971709719%2C1533106.2691529484%2C6924644.634147592&
width=768&height=641&srs=EPSG%3A3857&styles=&
format=image/jpeg

### Versions

occurs on 
kartoza/geoserver:2.25.1

### Additional context

seems to be a regression to 2.23 where we can not reproduce.

https://osgeo-org.atlassian.net/browse/GEOS-11417

**Comment by jeichhor** [comment]
already mentionid in https://github.com/kartoza/docker-geoserver/issues/653
