### ISSUE TITLE
Exception on starting

### ISSUE THREAD

**Issue by lderzhavets** [kartoza/docker-geoserver#99]
Getting this exception in latest version
Digest:sha256:df010edd6d24fff012fd10254036d94057c5e9357f379c86f84215c504568062

```
docker run kartoza/geoserver

SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/geoserver]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:731)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1868)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/geoserver] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.sqlite.SQLiteConnection->org.sqlite.jdbc4.JDBC4Connection->org.sqlite.jdbc3.JDBC3Connection->org.sqlite.SQLiteConnection]
        at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2098)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2044)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1989)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1959)
        at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1913)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1156)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:773)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:307)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        ... 10 more

12-Sep-2019 09:51:05.516 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Error deploying web application directory /usr/local/tomcat/webapps/geoserver
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/geoserver]]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:759)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:731)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1868)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

In the previous version (2.15.2) everything is OK

**Comment by NyakudyaA** [comment]
@lderzhavets I cannot replicate what you are getting
![pull](https://user-images.githubusercontent.com/2510900/64846924-14e5c700-d60e-11e9-83e1-cf50daeb0409.png)

![run](https://user-images.githubusercontent.com/2510900/64846933-1adba800-d60e-11e9-8d1c-1085e32c3df2.png)

Please pull the latest image first

**Comment by lderzhavets** [comment]
@NyakudyaA hmmm, I changed the port as yours 8082:8080 and it was OK, then I revert it to 8080:8080 and everuthing is OK again. Very strange, but ok, I think we can close the issue

**Comment by prebm** [comment]
This issue is occurring also when running version 2.15.0 from docker-compose. I am not sure what is causing it and it is not reproducible all the time. For example it didn't happen to me when using only:

```
docker run --name "geoserver" -p 8080:8080 -it kartoza/geoserver
```

Most of the time it happened to me when running with the files from this repo and explicitly specifying the geoserver.env.

```
version: '3.7'

volumes:
  geoserver-data:

services:

  geoserver:
    image: kartoza/geoserver:2.15.0
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - ../docker-env/geoserver.env
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

```

**Comment by NyakudyaA** [comment]
Hi @prebm Can you try explicitly specifying the environment variables and see if the error exists

**Comment by prebm** [comment]
@NyakudyaA when explicitly specifying the variables in the docker-compose.yml everything seems to be working. When applying the following changes the error seems to happen:

```
- INITIAL_MEMORY=1G
- MAXIMUM_MEMORY=2G
```

Is there a minimum memory limit? Using the same configuration for latest is working.

```
version: '3.7'

volumes:
  geoserver-data:

services:

  geoserver:
    image: kartoza/geoserver:2.15.0
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8080:8080"
    restart: on-failure
    # env_file:
    #   - ../docker-env/geoserver.env
    environment: 
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - ENABLE_JSONP=true
      - MAX_FILTER_RULES=20
      - OPTIMIZE_LINE_WIDTH=false
      - FOOTPRINTS_DATA_DIR=/opt/footprints_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_PASSWORD=myawesomegeoserver
      - INITIAL_MEMORY=1G
      - MAXIMUM_MEMORY=2G
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
```

**Comment by NyakudyaA** [comment]
> @NyakudyaA when explicitly specifying the variables in the docker-compose.yml everything seems to be working. When applying the following changes the error seems to happen:
> 
> ```
> - INITIAL_MEMORY=1G
> - MAXIMUM_MEMORY=2G
> ```
I will test with this setting. Have always let it run with the default settings
> 
> Is there a minimum memory limit? Using the same configuration for latest is working.
The 2.15.2 image does not contain these confirguration. The 2.15.0 image should work as is. I doubt there is a minimum confirguration. Please read this https://docs.geoserver.org/stable/en/user/production/container.html#optimize-your-jvm
> 
> ```
> version: '3.7'
> 
> volumes:
>   geoserver-data:
> 
> services:
> 
>   geoserver:
>     image: kartoza/geoserver:2.15.0
>     volumes:
>       - geoserver-data:/opt/geoserver/data_dir
>     ports:
>       - "8080:8080"
>     restart: on-failure
>     # env_file:
>     #   - ../docker-env/geoserver.env
>     environment: 
>       - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
>       - ENABLE_JSONP=true
>       - MAX_FILTER_RULES=20
>       - OPTIMIZE_LINE_WIDTH=false
>       - FOOTPRINTS_DATA_DIR=/opt/footprints_dir
>       - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
>       - GEOSERVER_ADMIN_PASSWORD=myawesomegeoserver
>       - INITIAL_MEMORY=1G
>       - MAXIMUM_MEMORY=2G
>     healthcheck:
>       test: curl --fail -s http://localhost:8080/ || exit 1
>       interval: 1m30s
>       timeout: 10s
>       retries: 3
> ```
So if you run this with the env file that has values that are changed it won't work ?

**Comment by prebm** [comment]
@NyakudyaA yes exactly, this configuration of docker-compose.yml with the specified environment variables is producing the error for me.
